config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end 
  resources :groups do
    collection do
      get :created_by_me
      get :where_i_am_member
    end  
    member do
      get :remove_member
      get :join_group
    end
  end  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :memberships
  has_many :members, through: :memberships, source: :user

  def self.owned_group(user)
  	self.where(owner_id: user.id)
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :owned_group, foreign_key: "owner_id", class_name: "Group"
  has_many :memberships
  has_many :groups, through: :memberships

  def is_join?(group)
    membership = Membership.where(user_id: self.id, group_id: group.id)
    membership.present?
  end

  def owner_group?(group) 
    self.id == group.owner_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
	  groups_path(current_user) # your path
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :find_group, only: [:show, :edit]
	def index
		@groups = Group.all
	end

	def new
		@group = Group.new
	end	

	def create
		@group = Group.new(group_params)
		@group.owner_id = current_user.id
		if @group.save
			 Membership.create(group_id: @group.id, user_id: current_user.id)
			redirect_to groups_path
		else
			render :new	
		end
	end

	def edit
	end

  def update
    @group = Group.find_by_id(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :new 
    end
  end  

	def show

	end

	def created_by_me
		@groups = Group.owned_group(current_user)
	end

	def join_group
		membership = Membership.new(group_id: params[:id], user_id: current_user.id)
		if membership.save
			redirect_to groups_path
		end
	end

  def remove_member
    membership = Membership.find_by(user_id: params[:user_id], group_id: params[:id])
    if membership.delete
      redirect_to group_path(params[:id])
    end
  end 

	def where_i_am_member
		@groups = current_user.groups
	end

	private

	def group_params
		params.require(:group).permit(:name)
	end	

	def find_group
		@group = Group.find_by_id(params[:id])
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="p-10  ml-5">
	<h2 class="font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600">Create/Edit Groups</h2>
</div>
<div class="">
	<%= form_with model: @group, local: true do |form| %>
	<div class=" p-10 ml-10">
		<span class="font-medium leading-tight text-3xl">Group name </span>
		<p>People will see this<br> name before joining<br> your group</p>
		<%= form.text_field :name, placeholder: "My Group", class: "ml-40" %>
	</div>
	<div class="">
			<%= form.submit "Create/Save", class: "p-10 ml-40 text-center block border border-yellow-500 rounded py-2 px-4 bg-yellow-500 hover:bg-yellow-700 text-white"%>
		<% end %>
	</div>
</div>

app/views/groups/created_by_me.html.erb
<div class="p-10  ml-5">
	<h2 class="font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600">Groups</h2>
</div>

<nav class="relative w-full flex flex-wrap items-center justify-between py-3 bg-gray-100 text-gray-500 hover:text-gray-700 focus:text-gray-700 shadow-lg">
  <div class="container-fluid w-full flex flex-wrap items-center justify-between px-6">
  	<ul class="flex ml-10">
  	  <li class="flex-1 mr-2">
				<%= link_to "All Groups", "/groups", class: "text-center block border border-blue-500 rounded py-2 px-4 bg-blue-500 hover:bg-blue-700 text-white" %>
  	  </li>
  	  <li class="flex-1 mr-2">
				<%= link_to "Created by me", "/groups/created_by_me", class: "text-center block border border-blue-700 rounded py-2 px-4 bg-blue-700 w-40 hover:bg-blue-700 text-white" %>
  	  </li>
  	  <li class="flex-1 mr-2">
				<%= link_to "Where I am member", "/groups/where_i_am_member", class: "text-center block border border-blue-500 rounded py-2 px-4 bg-blue-500 w-60 hover:bg-blue-700 text-white" %>
  	  </li>
  	</ul>
  	<ul class="flex float-right">
  	  <li class="flex-1 mr-2">
				<%= link_to "+ Create a new Group", "/groups/new", class: "text-center block border border-yellow-500 rounded py-2 px-4 bg-yellow-500 hover:bg-yellow-700 text-white" %>
  	  </li>
  	</ul>
  </div>
</nav>
<div class="text-center">
	<% @groups.each do |group| %>
		<div class="grid grid-cols-8 gap-8 mt-10 ml-56">
			<div class="font-medium leading-tight text-2xl"> <%= group.name %></div>
		</div>
	<% end %>
</div>

app/views/groups/edit.html.erb
<%= render "form" %>

app/views/groups/index.html.erb
<div class="p-10  ml-5">
	<h2 class="font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600">Groups</h2>
</div>

<nav class="relative w-full flex flex-wrap items-center justify-between py-3 bg-gray-100 text-gray-500 hover:text-gray-700 focus:text-gray-700 shadow-lg">
  <div class="container-fluid w-full flex flex-wrap items-center justify-between px-6">
  	<ul class="flex ml-10">
  	  <li class="flex-1 mr-2">
				<%= link_to "All Groups", "/groups", class: "text-center block border border-blue-700 rounded py-2 px-4 bg-blue-700 hover:bg-blue-700 text-white" %>
  	  </li>
  	  <li class="flex-1 mr-2">
				<%= link_to "Created by me", "/groups/created_by_me", class: "text-center block border border-blue-500 rounded py-2 px-4 bg-blue-500 w-40 hover:bg-blue-700 text-white" %>
  	  </li>
  	  <li class="flex-1 mr-2">
				<%= link_to "Where I am member", "/groups/where_i_am_member", class: "text-center block border border-blue-500 rounded py-2 px-4 bg-blue-500 w-60 hover:bg-blue-700 text-white" %>
  	  </li>
  	</ul>
  	<ul class="flex float-right">
  	  <li class="flex-1 mr-2">
				<%= link_to "+ Create a new Group", "/groups/new", class: "text-center block border border-yellow-500 rounded py-2 px-4 bg-yellow-500 hover:bg-yellow-700 text-white" %>
  	  </li>
  	</ul>
  </div>
</nav>
<div class="text-center">
	<% @groups.each do |group| %>
		<div class="grid grid-cols-8 gap-8 mt-10 ml-56">
			<% if group.owner_id == current_user.id %> 
				<div class="font-medium leading-tight text-2xl"> <%= link_to group.name, group_path(group) %></div><p>Created by you</p>
			<% else %>	
				<div class="font-medium leading-tight text-2xl"> <%= link_to group.name, group_path(group) %></div>
				<% if current_user.is_join?(group) %>
					<div> <%= link_to "Joined","javascript:void(0);" , class: "text-center block border border-orange-500 rounded py-2 px-4 bg-orange-500 hover:bg-orange-700 text-white"%></div>
				<% else %>	
					<div> <%= link_to "Join",join_group_group_path(group.id), class: "text-center block border border-orange-500 rounded py-2 px-4 bg-orange-500 hover:bg-orange-700 text-white"%></div>
				<% end %>	
			<% end %>	
		</div>
	<% end %>
</div>

app/views/groups/new.html.erb
<%= render "form" %>

app/views/groups/show.html.erb
<div class="grid grid-cols-5 gap-3">
  <div class="col-span-4">
    <div class="p-10  ml-5">
      <h2 class="font-medium leading-tight text-3xl mt-0 mb-2 text-blue-600">My Group <%= link_to '<i class="fa fa-cog" aria-hidden="true"></i>'.html_safe, edit_group_path(@group.id) %></h2>

    </div>
  </div>
  <div class="p-10  mr-5">
    <h2 class="font-medium leading-tight text-3xl mt-0 mb-2 text-blue-600">Members</h2>
    <% @group.members.each do |member| %>
      <% if member.id != current_user.id %>
        <h2 class="font-medium leading-tight text-xl mt-0 mb-2"><%= member.name %> 
          <% if current_user.owner_group?(@group) %>
            <%= link_to '<i class="fa fa-times" aria-hidden="true"></i>'.html_safe, remove_member_group_path(@group.id, user_id: member.id) %></h2>
          <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/groups/where_i_am_member.html.erb
<div class="p-10  ml-5">
	<h2 class="font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600">Groups</h2>
</div>

<nav class="relative w-full flex flex-wrap items-center justify-between py-3 bg-gray-100 text-gray-500 hover:text-gray-700 focus:text-gray-700 shadow-lg">
  <div class="container-fluid w-full flex flex-wrap items-center justify-between px-6">
  	<ul class="flex ml-10">
  	  <li class="flex-1 mr-2">
				<%= link_to "All Groups", "/groups", class: "text-center block border border-blue-500 rounded py-2 px-4 bg-blue-500 hover:bg-blue-700 text-white" %>
  	  </li>
  	  <li class="flex-1 mr-2">
				<%= link_to "Created by me", "/groups/created_by_me", class: "text-center block border border-blue-500 rounded py-2 px-4 bg-blue-500 w-40 hover:bg-blue-700 text-white" %>
  	  </li>
  	  <li class="flex-1 mr-2">
				<%= link_to "Where I am member", "/groups/where_i_am_member", class: "text-center block border border-blue-700 rounded py-2 px-4 bg-blue-700 w-60 hover:bg-blue-700 text-white" %>
  	  </li>
  	</ul>
  	<ul class="flex float-right">
  	  <li class="flex-1 mr-2">
				<%= link_to "+ Create a new Group", "/groups/new", class: "text-center block border border-yellow-500 rounded py-2 px-4 bg-yellow-500 hover:bg-yellow-700 text-white" %>
  	  </li>
  	</ul>
  </div>
</nav>
<div class="text-center">
	<% @groups.each do |group| %>
		<div class="grid grid-cols-8 gap-8 mt-10 ml-56">
			<div class="font-medium leading-tight text-2xl"> <%= group.name %></div>
		</div>
	<% end %>
</div>

app/views/layouts/_header.html.erb
<div class="bg-white  float-right p-5 text-xl">
	<%= link_to "Groups", "/groups", class: "mr-5 underline" %>	
	<%= link_to "Signout", destroy_user_session_path, :method => :delete %>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SImplero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>